FLAVOR_SUGGESTIONS: false
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - JSON_JSONLINT
  - JSON_V8R
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - POWERSHELL_POWERSHELL
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  #- SPELL_CSPELL # TODO enable when https://github.com/oxsecurity/megalinter/issues/2473 is fixed.
  - SPELL_MISSPELL
  - XML_XMLLINT
  - YAML_V8R
  - YAML_YAMLLINT
XML_XMLLINT_FILE_EXTENSIONS:
  - .xml
  - .xsl
PYTHON_MYPY_ARGUMENTS:
  - --cache-dir=/tmp
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - tmp
