collections:
  # see https://galaxy.ansible.com/ui/repo/published/ansible/windows
  - name: ansible.windows
    version: 3.0.0
  # see https://galaxy.ansible.com/ui/repo/published/chocolatey/chocolatey
  - name: chocolatey.chocolatey
    version: 1.5.3
  # see https://galaxy.ansible.com/ui/repo/published/community/general
  - name: community.general
    version: 10.7.0
  # see https://galaxy.ansible.com/ui/repo/published/community/windows
  - name: community.windows
    version: 3.0.0
