collections:
  # see https://galaxy.ansible.com/ansible/windows
  - name: ansible.windows
    version: 1.14.0
  # see https://galaxy.ansible.com/chocolatey/chocolatey
  - name: chocolatey.chocolatey
    version: 1.4.0
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 6.6.0
  # see https://galaxy.ansible.com/community/windows
  - name: community.windows
    version: 1.13.0
