collections:
  # see https://galaxy.ansible.com/ansible/windows
  - name: ansible.windows
    version: 1.11.1
  # see https://galaxy.ansible.com/chocolatey/chocolatey
  - name: chocolatey.chocolatey
    version: 1.3.1
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 5.7.0
  # see https://galaxy.ansible.com/community/windows
  - name: community.windows
    version: 1.11.0
