# see https://cli.github.com/telemetry
- name: Opt-out of telemetry
  ansible.windows.win_environment:
    level: machine
    name: DO_NOT_TRACK
    value: '1'

# see https://community.chocolatey.org/packages/gh
- name: Install github cli
  chocolatey.chocolatey.win_chocolatey:
    name: gh
    version: '{{ github_client_version }}'
    state: downgrade
