# opt-out of telemetry.
# see https://developer.hashicorp.com/packer/docs/configure#checkpoint_disable
- name: Opt-out of telemetry
  ansible.windows.win_environment:
    level: machine
    name: CHECKPOINT_DISABLE
    value: '1'

- name: Uninstall packer chocolatey package
  chocolatey.chocolatey.win_chocolatey:
    name: packer
    state: absent

- name: Install packer
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-packer.ps1') }}"
    parameters:
      version: '{{ packer_version }}'
