- name: Opt-out of telemetry
  ansible.windows.win_environment:
    level: machine
    name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

- name: Install dotnet-sdk
  chocolatey.chocolatey.win_chocolatey:
    name: dotnet-{{ (item | split('.'))[:2] | join('.') }}-sdk
    version: '{{ item }}'
    state: upgrade
  loop:
    - '{{ dotnet_sdk_lts_version }}'
    - '{{ dotnet_sdk_sts_version }}'

- name: Add the dotnet nuget nuget.org package source
  ansible.windows.win_powershell:
    # see https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source
    script: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = 'Stop'
      $ProgressPreference = 'SilentlyContinue'

      $sourceUrl = 'https://api.nuget.org/v3/index.json'

      $sources = dotnet nuget list source --format short | ForEach-Object {
        # e.g. E https://api.nuget.org/v3/index.json
        $parts = $_ -split '\s+',2
        if ($parts.Length -ne 2) {
          return
        }
        [PSCustomObject]@{
          Flags = $parts[0]
          SourceUrl = $parts[1]
        }
      }

      if ($sources -and $sources.SourceUrl -eq $sourceUrl) {
        $Ansible.Changed = $false
      } else {
        dotnet nuget add source --name nuget.org $sourceUrl
        if ($LASTEXITCODE) {
          throw "failed with exit code $LASTEXITCODE"
        }
        $Ansible.Changed = $true
      }
