# see https://github.com/hashicorp/packer/releases
# see https://releases.hashicorp.com/packer
# NB before upgrading be aware of:
#      https://github.com/hashicorp/packer/issues/13483
#      https://github.com/hashicorp/packer-plugin-qemu/issues/246
# renovate: datasource=github-releases depName=hashicorp/packer extractVersion=^v?(?<version>1\.14\.1)
packer_version: '1.14.1'
