# see https://www.visualstudio.com/vs/
# see https://visualstudio.microsoft.com/downloads/
# see https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-history
# see https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes
# see https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
# see https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples
# see https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids
# see https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022

- name: Enable the Windows Developer Mode
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    name: AllowDevelopmentWithoutDevLicense
    data: 1
    type: dword

- name: Install Visual Studio 2022
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2022community
    version: '{{ vs_version }}'
    state: upgrade

- name: Install Visual Studio 2022 Managed Desktop Workload
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2022-workload-manageddesktop
    state: upgrade

- name: Install Visual Studio 2022 Windows App SDK C# Templates # for WinUI.
  win_visual_studio_component:
    # see https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022
    name: Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cs
