# see https://community.chocolatey.org/packages/pwsh
# renovate: datasource=nuget:chocolatey depName=pwsh extractVersion=^(?<version>7\.2\..+)
pwsh_version: '7.2.10'

# see https://community.chocolatey.org/packages/firefox
# renovate: datasource=nuget:chocolatey depName=firefox
firefox_version: '111.0.1'

# see https://nmap.org/npcap/#download
# see https://github.com/nmap/npcap/releases
# renovate: datasource=github-releases depName=nmap/npcap
npcap_version: '1.73'
npcap_checksum: d5b309f7bd628712b3327212d76c631fbfc8f78a4f1ff3d0254f23552329c35d

# see https://community.chocolatey.org/packages/oh-my-posh
# see https://github.com/JanDeDobbeleer/oh-my-posh
# renovate: datasource=nuget:chocolatey depName=oh-my-posh
oh_my_posh_version: '14.29.3'

# see https://community.chocolatey.org/packages/git
# renovate: datasource=nuget:chocolatey depName=git
git_version: '2.40.0'
