# see https://community.chocolatey.org/packages/pwsh
# renovate: datasource=nuget:chocolatey depName=pwsh extractVersion=^(?<version>7\.2\..+)
base_pwsh_version: '7.2.14'

# see https://community.chocolatey.org/packages/firefox
# renovate: datasource=nuget:chocolatey depName=firefox
base_firefox_version: '118.0.2'

# see https://nmap.org/npcap/#download
# see https://github.com/nmap/npcap/releases
# renovate: datasource=github-releases depName=nmap/npcap
base_npcap_version: '1.77'

# see https://community.chocolatey.org/packages/oh-my-posh
# see https://github.com/JanDeDobbeleer/oh-my-posh
# renovate: datasource=nuget:chocolatey depName=oh-my-posh
base_oh_my_posh_version: '18.11.0'

# see https://community.chocolatey.org/packages/git
# renovate: datasource=nuget:chocolatey depName=git
base_git_version: '2.42.0'
