# see https://community.chocolatey.org/packages/firefox
# renovate: datasource=nuget depName=firefox
firefox_version: '108.0.1'

# see https://nmap.org/npcap/#download
# see https://github.com/nmap/npcap/releases
# renovate: datasource=github-releases depName=nmap/npcap
npcap_version: '1.72'
npcap_checksum: b0efd269d32e581da747e5050ef98d2eb91e6de9080e0918f5af85b485a4bdd1

# see https://community.chocolatey.org/packages/oh-my-posh
# see https://github.com/JanDeDobbeleer/oh-my-posh
# renovate: datasource=nuget depName=oh-my-posh
oh_my_posh_version: '12.30.1'

# see https://community.chocolatey.org/packages/git
# renovate: datasource=nuget depName=git
git_version: '2.39.0'
