# see https://ubuntu.com/blog/ubuntu-on-wsl-2-is-generally-available
# see https://learn.microsoft.com/en-us/windows/wsl/wsl-config
# see https://aka.ms/wsl2kernel
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl2.ps1
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl-ubuntu.ps1
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl-ubuntu.sh
# NB you can remove the distro altogether with:
#       wsl.exe --unregister Ubuntu-22.04
#       Remove-Item -Recurse C:\Wsl\Ubuntu-22.04

- name: Configure WSL Host
  # NB we disable wslg because it starts consuming too much cpu.
  #    and because I do not really need/use it.
  #    see wsl.exe --system -d Ubuntu top
  #    see https://github.com/microsoft/WSL/issues/6982
  #    see https://github.com/microsoft/wslg#wslg-system-distro
  ansible.windows.win_copy:
    src: .wslconfig
    dest: '%USERPROFILE%\.wslconfig'

- name: Install WSL Dependencies (Windows Server)
  when: ansible_os_installation_type != 'Client'
  block:
    - name: Install Hyper-V
      ansible.windows.win_feature:
        name: Hyper-V
        include_management_tools: true
      register: hyper_v_win_feature
    - name: Install WSL Windows feature
      ansible.windows.win_feature:
        # NB although in Windows 11 Client this is only required for WSL1, in
        #    Windows 2022 Server its required, or else, wsl.exe will fail with:
        #     This application requires the Windows Subsystem for Linux Optional Component.
        name: Microsoft-Windows-Subsystem-Linux
      register: wsl_win_feature
    - name: Reboot
      when: hyper_v_win_feature.reboot_required or wsl_win_feature.reboot_required
      ansible.windows.win_reboot:

- name: Install WSL Dependencies (Windows Client)
  when: ansible_os_installation_type == 'Client'
  block:
    - name: Install Virtual Machine Platform
      ansible.windows.win_optional_feature:
        name: VirtualMachinePlatform
      register: vmf_win_optional_feature
    - name: Uninstall WSL Windows feature
      ansible.windows.win_optional_feature:
        # NB in Windows 11 Client, this is only required for WSL1, which we
        #    do not use.
        name: Microsoft-Windows-Subsystem-Linux
        state: absent
      register: wsl_win_feature
    - name: Reboot
      when: vmf_win_optional_feature.reboot_required or wsl_win_feature.reboot_required
      ansible.windows.win_reboot:

- name: Install WSL
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-wsl.ps1') }}"
    parameters:
      version: '{{ wsl_version }}'

- name: Install WSL Ubuntu-22.04
  block:
    - name: Install WSL Ubuntu-22.04
      ansible.windows.win_powershell:
        script: "{{ lookup('file', 'install-wsl-ubuntu.ps1') }}"
        parameters:
          distroName: Ubuntu-22.04
          # see https://cloud-images.ubuntu.com/wsl
          distroUrl: 'https://cloud-images.ubuntu.com/wsl/jammy/current/ubuntu-jammy-wsl-amd64-wsl.rootfs.tar.gz'
    - name: Copy Ubuntu-22.04 icon
      ansible.windows.win_copy:
        # see https://findicons.com/icon/88935/ubuntu
        src: ubuntu-22.04.ico
        dest: C:\Wsl\ubuntu-22.04.ico
    - name: Install WSL Ubuntu-22.04 Start Menu Shortcut
      community.windows.win_shortcut:
        dest: C:\Users\All Users\Microsoft\Windows\Start Menu\Programs\Ubuntu-22.04.lnk
        icon: C:\Wsl\ubuntu-22.04.ico,0
        src: '%ProgramFiles%\WSL\wsl.exe'
        arguments: --distribution Ubuntu-22.04
        directory: '%USERPROFILE%'
