# see https://ubuntu.com/blog/ubuntu-on-wsl-2-is-generally-available
# see https://docs.microsoft.com/en-us/windows/wsl/wsl-config
# see https://aka.ms/wsl2kernel
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl2.ps1
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl-ubuntu.ps1
# see https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-wsl-ubuntu.sh
# NB you can remove the distro altogether with:
#       wsl.exe --unregister Ubuntu-20.04
#       Remove-Item -Recurse C:\Wsl\Ubuntu-20.04

- name: Install WSL Windows Optional Features
  ansible.windows.win_optional_feature:
    name:
      - Microsoft-Windows-Subsystem-Linux
      - VirtualMachinePlatform
  register: wsl

- name: Reboot
  when: wsl.reboot_required
  ansible.windows.win_reboot:

- name: Install WSL2 kernel
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-wsl2-kernel.ps1') }}"

- name: Set WSL default version
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'set-wsl-default-version.ps1') }}"

- name: Install WSL Ubuntu
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-wsl-ubuntu.ps1') }}"

- name: Install WSL Ubuntu Shortcut
  block:
    - name: Copy Ubuntu icon
      ansible.windows.win_copy:
        # see https://findicons.com/icon/88935/ubuntu
        src: ubuntu.ico
        dest: C:\Wsl\Ubuntu-20.04\ubuntu.ico
    - name: Install WSL Ubuntu Start Menu Shortcut
      community.windows.win_shortcut:
        dest: C:\Users\All Users\Microsoft\Windows\Start Menu\Programs\Ubuntu.lnk
        icon: C:\Wsl\Ubuntu-20.04\ubuntu.ico,0
        src: wsl.exe
        arguments: --distribution Ubuntu-20.04
        directory: '%USERPROFILE%'
    - name: Install WSL Ubuntu Desktop Shortcut
      community.windows.win_shortcut:
        dest: '%USERPROFILE%\Desktop\Ubuntu.lnk'
        icon: C:\Wsl\Ubuntu-20.04\ubuntu.ico,0
        src: wsl.exe
        arguments: --distribution Ubuntu-20.04
        directory: '%USERPROFILE%'
