- name: Install Hyper-V (Windows Server)
  when: ansible_os_installation_type != 'Client'
  block:
    - name: Install Hyper-V (Windows Server)
      ansible.windows.win_feature:
        name: Hyper-V
        include_management_tools: true
      register: hyper_v_win_feature
    - name: Reboot
      when: hyper_v_win_feature.reboot_required
      ansible.windows.win_reboot:

- name: Install Hyper-V (Windows Client)
  when: ansible_os_installation_type == 'Client'
  block:
    - name: Install Hyper-V (Windows Client)
      ansible.windows.win_optional_feature:
        name: Microsoft-Hyper-V-All
      register: hyper_v_win_feature
    - name: Reboot
      when: hyper_v_win_feature.reboot_required
      ansible.windows.win_reboot:

- name: Create the Vagrant vSwitch
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-vagrant-vswitch.ps1') }}"

- name: Remove the Vagrant vSwitch from the Windows Firewall
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'remove-vagrant-vswitch-from-firewall.ps1') }}"

- name: Install WinDHCP
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-windhcp.ps1') }}"
    parameters:
      version: '{{ hyper_v_windhcp_version }}'
      checksum: '{{ hyper_v_windhcp_checksum }}'
  notify:
    - Restart WinDHCP
