- name: Install vscode
  chocolatey.chocolatey.win_chocolatey:
    name: vscode
    version: '{{ vscode_version }}'
    pinned: true
    state: upgrade

- name: Create the configuration directory
  ansible.windows.win_file:
    path: '%APPDATA%\Code\User'
    state: directory

- name: Configure vscode
  ansible.windows.win_copy:
    src: settings.json
    dest: '%APPDATA%\Code\User\settings.json'

# TODO install extensions.
