- name: Install vscode
  chocolatey.chocolatey.win_chocolatey:
    name: vscode
    version: '{{ vscode_version }}'
    state: upgrade

- name: Create the configuration directory
  ansible.windows.win_file:
    path: '%APPDATA%\Code\User'
    state: directory

- name: Configure vscode
  ansible.windows.win_copy:
    src: settings.json
    dest: '%APPDATA%\Code\User\settings.json'

- name: Install extensions
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-extensions.ps1') }}"
    parameters:
      extensions:
        - dotjoshjohnson.xml
        - golang.go
        - hashicorp.hcl
        - hashicorp.terraform
        - ms-azuretools.vscode-docker
        - ms-dotnettools.csharp
        - ms-python.python
        # Remote - SSH.
        # see https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
        - ms-vscode-remote.remote-ssh
        # WSL.
        # see https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
        - ms-vscode-remote.remote-wsl
        # PowerShell.
        # see https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell
        - ms-vscode.powershell
        # Makefile Tools.
        # see https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools
        - ms-vscode.makefile-tools
        # Jinja Template Highlighting.
        # see https://github.com/samuelcolvin/jinjahtml-vscode
        # see https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml
        # NB be aware of https://github.com/microsoft/vscode/issues/49210
        - samuelcolvin.jinjahtml
        # Spell checker.
        # see https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
        - streetsidesoftware.code-spell-checker
        # see https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-portuguese
        - streetsidesoftware.code-spell-checker-portuguese
        # Rust language support.
        # see https://github.com/rust-lang/rust-analyzer
        # see https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer
        - rust-lang.rust-analyzer
        # Svelte language support.
        # see https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
        - svelte.svelte-vscode
        # GitHub Actions.
        # see https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions
        - github.vscode-github-actions
