- name: Install aws cli
  chocolatey.chocolatey.win_chocolatey:
    # see https://community.chocolatey.org/packages/awscli
    name: awscli
    version: '{{ aws_client_aws_version }}'
    state: downgrade

- name: Install aws session-manager-plugin
  chocolatey.chocolatey.win_chocolatey:
    # see https://community.chocolatey.org/packages/awscli-session-manager
    name: awscli-session-manager
    version: '{{ aws_client_session_manager_plugin_version }}'
    state: downgrade

# NB this is uninstalled because it clobbers the AWS.Tools modules.
- name: Uninstall AWSPowerShell.NetCore PowerShell Module
  community.windows.win_psmodule:
    name: AWSPowerShell.NetCore
    accept_license: true
    state: absent

- name: Install AWS.Tools PowerShell Modules
  community.windows.win_psmodule:
    name: '{{ item }}'
    required_version: '{{ aws_client_aws_ps_version }}'
    accept_license: true
    state: present
  loop:
    - AWS.Tools.SecretsManager
    - AWS.Tools.EC2
    - AWS.Tools.S3
