- name: Install Firefox
  chocolatey.chocolatey.win_chocolatey:
    # https://community.chocolatey.org/packages/firefox
    name: firefox
    version: '{{ base_firefox_version }}'
    package_params: /l:en-US
    state: downgrade

- name: Install SetDefaultBrowser
  chocolatey.chocolatey.win_chocolatey:
    # https://community.chocolatey.org/packages/setdefaultbrowser
    name: setdefaultbrowser
    version: '{{ base_setdefaultbrowser_version }}'
    state: downgrade

- name: Set Firefox as the default browser
  ansible.windows.win_powershell:
    script: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = 'Stop'
      $ProgressPreference = 'SilentlyContinue'
      $Ansible.Changed = $false
      $browser = @((SetDefaultBrowser | Where-Object {$_ -like 'HKLM Firefox-*'}) -split ' ')
      $browserId = $browser[1]
      $path = "$($Ansible.Tmpdir)\AppAssociations.xml"
      Dism /Online "/Export-DefaultAppAssociations:$path"
      [xml]$doc = Get-Content $path
      $node = $doc.SelectSingleNode("/DefaultAssociations/Association[@ApplicationName='Firefox']")
      if (!$node) {
        SetDefaultBrowser @browser
        $Ansible.Changed = $true
      }
