- name: Disable update notifications
  # see https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.2
  ansible.windows.win_environment:
    level: machine
    name: POWERSHELL_UPDATECHECK
    value: 'Off'

- name: Install pwsh
  chocolatey.chocolatey.win_chocolatey:
    # https://community.chocolatey.org/packages/pwsh
    name: pwsh
    version: '{{ pwsh_version }}'
    state: upgrade
