- name: Install the Windows Terminal
  # NB Windows Terminal requires Windows 10 1903 build 18362+.
  when:
    - ansible_distribution_version is version('10.0.18362.0', '>=')
  vars:
    # see https://www.nuget.org/packages/Microsoft.UI.Xaml
    # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/dep/nuget/packages.config#L10C78-L10C78
    # renovate: datasource=nuget depName=Microsoft.UI.Xaml extractVersion=^(?<version>2\.8\..+)
    windows_terminal_xaml_dependency_version: '2.8.5'
    # see https://community.chocolatey.org/packages/microsoft-windows-terminal
    # see https://github.com/microsoft/terminal/releases
    # renovate: datasource=nuget:chocolatey depName=microsoft-windows-terminal
    base_windows_terminal_version: '1.18.3181.0'
    base_windows_terminal_package_publisher_id: 8wekyb3d8bbwe
    base_windows_terminal_package_name: Microsoft.WindowsTerminal
    base_windows_terminal_package_family_name: '{{ base_windows_terminal_package_name }}_{{ base_windows_terminal_package_publisher_id }}'
    base_windows_terminal_package_full_name: '{{ base_windows_terminal_package_name }}_{{ base_windows_terminal_version }}_x64__{{ base_windows_terminal_package_publisher_id }}' # noqa yaml[line-length]
  block:
    - name: Install the Visual C++ Universal Runtime Desktop Bridge dependency
      # see https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge
      # see https://github.com/mkevenaar/chocolatey-packages/issues/124
      # NB this is required because our Windows Base Image do not have the Windows Store installed.
      ansible.windows.win_package:
        product_id: Microsoft.VCLibs.140.00.UWPDesktop
        path: https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx
    - name: Install the Windows Terminal dependencies
      ansible.windows.win_powershell:
        script: "{{ lookup('file', 'install-windows-terminal-dependencies.ps1') }}"
        parameters:
          xaml_dependency_version: '{{ windows_terminal_xaml_dependency_version }}'
    - name: Install the Windows Terminal
      chocolatey.chocolatey.win_chocolatey:
        name: microsoft-windows-terminal
        version: '{{ base_windows_terminal_version }}'
        state: upgrade
    - name: Create the Windows Terminal LocalState directory
      ansible.windows.win_file:
        path: '%LOCALAPPDATA%\Packages\{{ base_windows_terminal_package_family_name }}\LocalState'
        state: directory
    - name: Configure the Windows Terminal
      ansible.windows.win_copy:
        src: windows-terminal-settings.json
        dest: '%LOCALAPPDATA%\Packages\{{ base_windows_terminal_package_family_name }}\LocalState\settings.json'
    - name: Set the Windows Terminal as the Default Terminal Application
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/doc/specs/%23492%20-%20Default%20Terminal/spec.md
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/src/cascadia/TerminalSettingsModel/CascadiaSettings.h#L138-L144
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp#L1128-L1131
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/src/cascadia/TerminalSettingsModel/DefaultTerminal.cpp#L76-L84
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/src/propslib/DelegationConfig.cpp#L158-L174
      # see https://github.com/microsoft/terminal/blob/v1.18.3181.0/src/propslib/DelegationConfig.cpp#L35-L36
      # see https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.appextensions.appextensioncatalog?view=winrt-22621
      # see HKEY_CLASSES_ROOT\PackagedCom\ClassIndex\{E12CFF52-A866-4C77-9A90-F570A7AA2C6B}\Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe
      # see HKEY_CLASSES_ROOT\PackagedCom\Package\Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe\Class\{E12CFF52-A866-4C77-9A90-F570A7AA2C6B}
      block:
        - name: Set the Windows Terminal as the Default Console Application
          ansible.windows.win_regedit:
            path: HKCU:\Console\%%Startup
            name: DelegationConsole
            data: '{2EACA947-7F5F-4CFA-BA87-8F7FBEEFBE69}'
            type: string
        - name: Set the Windows Terminal as the Default Terminal Application
          ansible.windows.win_regedit:
            path: HKCU:\Console\%%Startup
            name: DelegationTerminal
            data: '{E12CFF52-A866-4C77-9A90-F570A7AA2C6B}'
            type: string
    - name: Install the Windows Terminal shortcut
      block:
        - name: Get installed Windows Terminal path
          register: base_windows_terminal_path_result
          ansible.windows.win_powershell:
            # NB we need to explicitly grab the package version, because, the
            #    windows terminal package seems to be automatically updated,
            #    and when that happens, we want the shortcut to reflect that.
            script: |
              Set-StrictMode -Version Latest
              $ErrorActionPreference = 'Stop'
              $ProgressPreference = 'SilentlyContinue'
              $Ansible.Changed = $false
              $windowsTerminalPath = 'C:\Program Files\WindowsApps\{{ base_windows_terminal_package_full_name }}\WindowsTerminal.exe'
              $package = Get-AppxPackage `
                -Name '{{ base_windows_terminal_package_name }}' `
                -ErrorAction SilentlyContinue `
                | Where-Object {
                  $_.PublisherId -eq '{{ base_windows_terminal_package_publisher_id }}'
                }
              if ($package) {
                $windowsTerminalPath = Join-Path $package.InstallLocation WindowsTerminal.exe
              }
              $Ansible.Result = @{
                # NB the "App" part ar the end of this string was obtained with
                #    the following Windows PowerShell snippet:
                #     (Get-AppxPackageManifest (Get-AppxPackage Microsoft.WindowsTerminal)).Package.Applications.Application.Id
                windows_terminal_path = 'shell:AppsFolder\{{ base_windows_terminal_package_family_name }}!App'
                windows_terminal_icon_path = "$windowsTerminalPath,0"
              }
        - name: Install the Windows Terminal shortcut
          community.windows.win_shortcut:
            dest: '%USERPROFILE%\Desktop\Windows Terminal.lnk'
            description: Windows Terminal
            src: explorer.exe
            args: '{{ base_windows_terminal_path_result.result.windows_terminal_path }}'
            icon: '{{ base_windows_terminal_path_result.result.windows_terminal_icon_path }}'
