- name: Install Hyper-V (Windows Server)
  when: ansible_os_installation_type != 'Client'
  ansible.windows.win_feature:
    name: Hyper-V
    include_management_tools: yes
  register: hyper_v

- name: Install Hyper-V (Windows Client)
  when: ansible_os_installation_type == 'Client'
  ansible.windows.win_optional_feature:
    name: Microsoft-Hyper-V-All
  register: hyper_v

- name: Reboot
  when: hyper_v.reboot_required
  ansible.windows.win_reboot:

- name: Create the Vagrant vSwitch
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-vagrant-vswitch.ps1') }}"

- name: Install WinDHCP
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'install-windhcp.ps1') }}"
    parameters:
      version: '{{ windhcp_version }}'
      checksum: '{{ windhcp_checksum }}'
  notify:
    - restart WinDHCP
