# see https://www.visualstudio.com/vs/
# see https://visualstudio.microsoft.com/downloads/
# see https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-history
# see https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes
# see https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
# see https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples
# see https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids
# see https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022

- name: Enable the Windows Developer Mode
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    name: AllowDevelopmentWithoutDevLicense
    data: 1
    type: dword

- name: Install Visual Studio
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2022community
    version: '{{ vs_version }}'
    state: upgrade

- name: Install Managed Desktop Component
  win_visual_studio_component: # noqa fqcn[action]
    name:
      - Microsoft.NetCore.Component.DevelopmentTools # Development tools for .NET
      - Microsoft.VisualStudio.Workload.ManagedDesktop # .NET desktop development

- name: Install Native Desktop Component
  win_visual_studio_component: # noqa fqcn[action]
    name: Microsoft.VisualStudio.Workload.NativeDesktop # Desktop development with C++

- name: Install Visual C++ Tools Component
  win_visual_studio_component: # noqa fqcn[action]
    name: Microsoft.VisualStudio.Component.VC.Tools.x86.x64 # MSVC v143 - VS 2022 C++ x64/x86 build tools

- name: Install Windows 10 SDK 19041 Component
  win_visual_studio_component: # noqa fqcn[action]
    name: Microsoft.VisualStudio.Component.Windows10SDK.19041 # Windows 10 SDK (10.0.19041.0)

- name: Install Windows App SDK C# Templates Component # for WinUI.
  win_visual_studio_component: # noqa fqcn[action]
    name: Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cs # Windows App SDK C# Templates

- name: Configure Visual Studio
  # NB tracking the .vssettings changes is too hard to implement. mainly,
  #    because when visual studio closes, it modifies the file in an
  #    unpredictable way (e.g. xml elements and attributes are re-ordered),
  #    so this will only set the settings when no .vssettings exists.
  # NB to redo this after visual studio is started, you have to delete the
  #    whole settings directory:
  #     Remove-Item -Recurse -Force "$env:LOCALAPPDATA\Microsoft\VisualStudio"
  block:
    - name: Install local configuration directory
      ansible.windows.win_file:
        path: '%USERPROFILE%\.ansible-visual-studio'
        state: directory
    - name: Install local settings.xsl
      ansible.windows.win_copy:
        src: settings.xsl
        dest: '%USERPROFILE%\.ansible-visual-studio\settings.xsl'
    - name: Configure Settings
      ansible.windows.win_powershell:
        script: "{{ lookup('file', 'settings.ps1') }}"
