# see https://community.chocolatey.org/packages/azure-cli
# see https://github.com/Azure/azure-cli/releases
# renovate: datasource=nuget:chocolatey depName=azure-cli
azure_client_azure_cli_version: '2.77.0'
